# docker-compose.yml
version: '3.8'
services:
    db:
        image: postgres:15
        container_name: nest_postgres
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: nestuser
            POSTGRES_PASSWORD: nestpass
            POSTGRES_DB: nestdb
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:
